param(
    [Parameter(Mandatory=$true)]
    [string]$ScriptPath
)

$outputFile = "$env:TEMP\script_output.txt"

Write-Output "Verifying script: $ScriptPath"
if (-not (Test-Path $ScriptPath)) {
    Write-Error "File not found: $ScriptPath"
    exit 1
}

Write-Output "Running script with administrator privileges..."
Start-Process powershell.exe -Verb RunAs -ArgumentList @(
    '-NoProfile',
    '-WindowStyle', 'Hidden',
    '-ExecutionPolicy', 'Bypass',
    '-Command', "& {
        try {
            Write-Output 'Starting script execution...'
            & '$ScriptPath' *>&1 | Out-File -FilePath '$outputFile' -Append
            Write-Output 'SCRIPT_COMPLETED'
        } catch {
            Write-Error `$_.Exception.Message
            Write-Output 'SCRIPT_FAILED'
            exit 1
        }
    }"
) -Wait

if (Test-Path $outputFile) {
    Get-Content $outputFile
    Remove-Item $outputFile
} else {
    Write-Output "No output was generated by the script."
} 